//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualLocalizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSPackage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualLocalizer.VSPackage", typeof(VSPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Localizer.
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDH8CPQ1JEIZZMC8EIHMAKHRKPQDCTEKKRM9I9ZDKDIKCMHRPRI1KMR0MZZMQDR2IJIDJCM0IJJ3Z9R8M0KHCDEKJMETCHD1D9RAEAQRRPDZJMJZRQI0AKA9CIMMQ3QE.
        /// </summary>
        internal static string _111 {
            get {
                return ResourceManager.GetString("111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool for advanced manipulation with resources..
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Localizer ResX Editor.
        /// </summary>
        internal static string _113 {
            get {
                return ResourceManager.GetString("113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralSettings.
        /// </summary>
        internal static string _114 {
            get {
                return ResourceManager.GetString("114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Localizer.
        /// </summary>
        internal static string _115 {
            get {
                return ResourceManager.GetString("115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings used by Visual Localizer package. .
        /// </summary>
        internal static string _116 {
            get {
                return ResourceManager.GetString("116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterSettings.
        /// </summary>
        internal static string _117 {
            get {
                return ResourceManager.GetString("117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter settings.
        /// </summary>
        internal static string _118 {
            get {
                return ResourceManager.GetString("118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences from Batch Move to Resources toolwindow (filters, regexps...).
        /// </summary>
        internal static string _119 {
            get {
                return ResourceManager.GetString("119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Localizer.
        /// </summary>
        internal static string _123 {
            get {
                return ResourceManager.GetString("123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter ToolWindows.
        /// </summary>
        internal static string _124 {
            get {
                return ResourceManager.GetString("124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string _126 {
            get {
                return ResourceManager.GetString("126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorSettings.
        /// </summary>
        internal static string _127 {
            get {
                return ResourceManager.GetString("127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor settings.
        /// </summary>
        internal static string _128 {
            get {
                return ResourceManager.GetString("128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizations of ResX files editor..
        /// </summary>
        internal static string _129 {
            get {
                return ResourceManager.GetString("129", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _501 {
            get {
                object obj = ResourceManager.GetObject("501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _502 {
            get {
                object obj = ResourceManager.GetObject("502", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
